build:
  image: node:9.11.1
  cache:
    paths:
    - node_modules/
  stage: build
  script:
  - yarn install # npm install
  - yarn build # npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
  - master
 
deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete public/ gitlab@"$server":/www/