build:
  image: node:12.17.0
  cache:
    paths:
    - node_modules/
  stage: build
  script:
  - yarn install # npm install
  - yarn build # npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
  - master
 
deploy:
  image: ubuntu:20.04
  stage: deploy
  before_script:
  - sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
  - apt update
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt-get install -y -q
  - 'which ssh-agent || ( apt install -y ssh )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\nHost *\n\tPort $port\n\n" > ~/.ssh/config'
  script:
    - apt install -y rsync ripgrep fonttools
    - cd public/
    - pyftsubset "assets/fonts/lxgw.513297f3.ttf" --text=$(rg ./ -e '[\w\d]' -oN --no-filename|sort|uniq|tr -d '\n') --no-hinting
    - mv assets/fonts/lxgw.513297f3.ttf assets/fonts/lxgw.513297f3.ttf.bak
    - mv assets/fonts/lxgw.513297f3.subset.ttf assets/fonts/lxgw.513297f3.ttf
    - cd ..
    - rsync -rav --delete public/ gitlab@"$server":/www/$CI_PROJECT_NAME/