build:
  image: node:12.17.0
  cache:
    paths:
    - node_modules/
  stage: build
  script:
  - yarn install # npm install
  - yarn build # npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
  - master
 
deploy:
  image: alpine
  stage: deploy
  before_script:
  - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
  - apk update
  - 'which ssh-agent || ( apk add --no-cache openssh )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\nHost *\n\tPort $port\n\n" > ~/.ssh/config'
  script:
    - echo trigger deploy
    - apk add --no-cache rsync
    - rsync -rav --delete public/ gitlab@"$server":/www/$CI_PROJECT_NAME/